name: Nightly Release

on:
  push:
    branches:
      - develop

jobs:
  nightly-release:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Bump version (canary)
      id: bump-version
      run: |
        SHORT_VERSION=$(python3 update-version.py get-version --short)
        NEW_VERSION="${SHORT_VERSION}-SNAPSHOT-$(git rev-parse --short HEAD)"
        NEW_ASSEMBLY_VERSION="${SHORT_VERSION}.0"
        python3 update-version.py update-version --new-version "$NEW_VERSION" --new-assembly-version $NEW_ASSEMBLY_VERSION
        git --no-pager diff
        echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
    - id: build-mod
      uses: ./.github/actions/build-mod
      with:
        ksp_dlls_donwload_url: ${{ secrets.KSP_DLLS_DONWLOAD_URL }}
        ksp_dlls_password: ${{ secrets.KSP_DLLS_PASSWORD }}
        tmp_path: ${{ runner.temp }}
    - name: Preparing Release files
      id: release-files
      run: |
        mkdir -p $RUNNER_TEMP/release
        ZIP_FILENAME="BetterRocketDesigns-v${{ steps.bump-version.outputs.new_version }}.zip"
        mv ${{ steps.build-mod.outputs.zip_path }} $RUNNER_TEMP/release/$ZIP_FILENAME
        echo "release_zip=$RUNNER_TEMP/release/$ZIP_FILENAME" >> $GITHUB_OUTPUT
    - name: Delete latest canary release
      run: gh release delete canary -y || true
    - name: Release new canary
      run: gh release create canary --prerelease --generate-notes --target develop --title 'Canary (v${{ steps.bump-version.outputs.new_version }})' '${{ steps.release-files.outputs.release_zip }}'
