name: Nightly Release

on:
  push:
    branches:
      - develop

jobs:
  nightly-release:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    # - name: Bump version (canary)
    #   run: python3 update-version.py TODO
    - id: build-mod
      uses: ./.github/actions/build-mod
      with:
        ksp_dlls_donwload_url: ${{ secrets.KSP_DLLS_DONWLOAD_URL }}
        ksp_dlls_password: ${{ secrets.KSP_DLLS_PASSWORD }}
        tmp_path: ${{ runner.temp }}
    - name: Preparing Release files
      id: release-files
      run: |
        mkdir -p $RUNNER_TEMP/release
        mv ${{ steps.build-mod.outputs.zip_path }} $RUNNER_TEMP/release/BetterRocketDesigns-${{ github.ref_name }}.zip
        echo "release_zip=$RUNNER_TEMP/release/BetterRocketDesigns-${{ github.ref_name }}.zip" >> $GITHUB_OUTPUT
    - name: Check if canary tag exists
      run: gh release view canary
    - name: Delete latest canary release
      if: failure()
      run: gh release delete canary -y
    - name: Release new canary
      run: gh release create canary ${{ steps.release-files.outputs.release_zip }}
