name: make-release

on:
  workflow_dispatch:
    inputs:
        new_version:
            type: string
            required: true

jobs:
  make-release:
    runs-on: ubuntu-latest
    steps:
      - name: Validate requirements
        run: |
          [[ "${{ inputs.new_version }}" ]] || { echo "new_version input is empty" ; exit 1; }
      - uses: actions/checkout@v4
      - name: Bummping version
        run: |
          NEW_VERSION=${{ inputs.new_version }}
          NEW_ASSEMBLY_VERSION="${SHORT_VERSION}.0"
          python3 update-version.py update-version --new-version ${{ inputs.new_version }} --new-assembly-version $NEW_ASSEMBLY_VERSION
      - run: git status
      - name: Setup git config
        run: |
          git config user.name "Github Actions Bot"
          git config user.email "<>"
      - name: Finalizing release - Git
        run: |
          RELEASE_BRANCH="release/v${{ inputs.new_version }}"
          git checkout -b $RELEASE_BRANCH
          git add *
          git commit -m "New release BetterRocketDesigns v${{ inputs.new_version }}"
          git checkout master
          git merge --no-ff $RELEASE_BRANCH -m "Merge branch '$RELEASE_BRANCH' into master"
          git tag -a "v${{ inputs.new_version }}" -m "New release BetterRocketDesigns v${{ inputs.new_version }}"
          git checkout develop
          git merge master
          git push origin master develop --tags