name: publish

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: build-mod
        uses: ./.github/actions/build-mod
        with:
          ksp_dlls_donwload_url: ${{ secrets.KSP_DLLS_DONWLOAD_URL }}
          ksp_dlls_password: ${{ secrets.KSP_DLLS_PASSWORD }}
          tmp_path: ${{ runner.temp }}
      - name: Preparing Release files
        id: release-files
        run: |
          mkdir -p $RUNNER_TEMP/release
          mv ${{ steps.build-mod.outputs.zip_path }} $RUNNER_TEMP/release/BetterRocketDesigns-${{ github.ref_name }}.zip
          echo "release_zip=$RUNNER_TEMP/release/BetterRocketDesigns-${{ github.ref_name }}.zip" >> $GITHUB_OUTPUT
      - name: Upload release artifacts
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create ${{ github.ref_name }} ${{ steps.release-files.outputs.release_zip }}
          