name: better-rocket-designs

on:
  push:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Validate requirements
        id: validate-requirements
        run: |
          if [ -z "${{ secrets.KSP_DLLS_DONWLOAD_URL }}" ]; then
            echo "Error: KSP_DLLS_DONWLOAD_URL secret is missing."
            exit 1
          fi
      - uses: actions/checkout@v4
      - name: Download KSP Assemblies (Dlls)
        id: download-assemblies
        run: |
          curl "${{ secrets.KSP_DLLS_DONWLOAD_URL }}" -L --output $RUNNER_TEMP/dlls.zip
          unzip $RUNNER_TEMP/dlls.zip -d $RUNNER_TEMP/dlls
          echo "ksp_dlls_path=$RUNNER_TEMP/dlls/ksp-assemblies" >> $GITHUB_OUTPUT
      - id: building
        run: |
          make DLLS_PATH=${{ steps.download-assemblies.outputs.ksp_dlls_path }}
          echo "release_zip_path=$GITHUB_WORKSPACE/build/bin/Release/BetterRocketDesigns.zip" >> $GITHUB_OUTPUT
      - name: Final step
        id: final-step
        run: |
          unzip -d $RUNNER_TEMP/destination ${{ steps.building.outputs.release_zip_path }}
          find $RUNNER_TEMP